<?xml version="1.0" encoding="UTF-8"?>
<project name="Quizora" default="run" basedir=".">
    <property name="src.dir" value="src"/>
    <property name="build.dir" value="build"/>
    <property name="classes.dir" value="${build.dir}/classes"/>
    <property name="lib.dir" value="lib"/>
    <property name="main.class" value="com.quizora.App"/>

    <path id="classpath">
        <fileset dir="${lib.dir}" includes="**/*.jar"/>
    </path>

    <target name="init">
        <mkdir dir="${build.dir}"/>
        <mkdir dir="${classes.dir}"/>
        <mkdir dir="${lib.dir}"/>
    </target>

    <target name="compile" depends="init">
        <javac srcdir="${src.dir}"
               destdir="${classes.dir}"
               classpathref="classpath"
               includeantruntime="false"
               source="17"
               target="17"/>
    </target>

    <target name="run" depends="compile">
        <java classname="${main.class}" fork="true">
            <classpath path="${classes.dir}"/>
            <classpath refid="classpath"/>
        </java>
    </target>

    <target name="clean">
        <delete dir="${build.dir}"/>
    </target>
</project>
